package com.ecommerce.platform.entity;

public enum NotificationType {
	
	WELCOME,
	ORDER_CREATED,
	PAYMENT_SUCCESS,
	PAYMENT_FAILED,
	SHIPMENT_CREATED,
	SHIPMENT_SHIPPED,
	SHIPMENT_OUT_FOR_DELIVERY,
	SHIPMENT_DELIVERED,
	ORDER_CANCELLED,
	PASSWORD_CHANGED,
	PROFILE_UPDATED

}
