spring.application.name=user-services

server.port= 6868
#PsotgresSQL Connection:

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Hibernate

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format_sql = true

#It is True by default> That keeps the Hibernate Session open until the response is returned. but for better performance we will set it to false
spring.jpa.open-in-view= false 

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000